[package]
name = "chessie"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "chessie-pregen"
path = "src/bin/pregen.rs"

[[bin]]
name = "chessie"
path = "src/bin/main.rs"

[dependencies]
rand = "0.8.5"
test-case = "3.3.1"
